config/routes.rb
GameHub::Application.routes.draw do
  resources :levels

  root to: 'static_pages#home'
  get "static_pages/home"

  match "create", to: "Levels#create", via: :post
  match "levels/download/:id", to: "Levels#load"
  match "replay/:id", to: "static_pages#home"

end

app/models/level.rb
class Level < ActiveRecord::Base
  attr_accessible :enemies, :objects, :tiles, :icon
  has_attached_file :icon
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/levels_controller.rb
class LevelsController < ApplicationController
  # GET /levels
  # GET /levels.json

  #skip_before_filter :verify_authenticity_token, only: :create

  def index
    @levels_latest = Level.limit(10).order("created_at desc").all
    @levels_popular = Level.limit(10).order("plays desc").all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @levels }
    end
  end

  # GET /levels/1
  # GET /levels/1.json
  def show
    @level = Level.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @level }
    end
  end

  # GET /levels/new
  # GET /levels/new.json
  def new
    @level = Level.new
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @level }
    end
  end

  # GET /levels/1/edit
  def edit
    @level = Level.find(params[:id])
  end

  # POST /levels
  # POST /levels.json
  def create
    @level = Level.find_by_tiles_and_objects_and_enemies(params[:tiles], params[:objects], params[:enemies])
    
    if @level
      render json: @level, status: :created, location: @level
    else
      path = File.join("public/levels/icons", "#{Time.now.getutc}.png")
      file = File.open(path, "wb") { |f| f.write(Base64.decode64(params[:icon])) }

      file = File.open(path, "r")
      @level = Level.new(tiles: params[:tiles], objects: params[:objects], enemies: params[:enemies], icon: file)
      file.close

      if @level.save
        #create_icon_for @level
        render json: @level, status: :created, location: @level
      else
        render json: @level.errors, status: :unprocessable_entity
      end
    end
  end

  def create_icon_for(level)
    #file = File.open()
    #path = File.join("public/levels/icons", "#{@level.id}.png")
    #File.open(path, "wb") { |f| f.write(Base64.decode64(params[:icon])) }
  end

  # PUT /levels/1
  # PUT /levels/1.json
  def update
 #   @level = Level.find(params[:id])

#    respond_to do |format|
#      if @level.update_attributes(params[:level])
#        format.html { redirect_to @level, notice: 'Level was successfully updated.' }
#        format.json { head :no_content }
#      else
#        format.html { render action: "edit" }
#        format.json { render json: @level.errors, status: :unprocessable_entity }
#      end
#    end
  end

  # DELETE /levels/1
  # DELETE /levels/1.json
  def destroy
  end

  def load
    @level = Level.find(params[:id])
    @level.update_attribute(:plays, @level.plays + 1)

    render json: @level
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  	@replay = params[:id] || ""
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/levels_helper.rb
module LevelsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
  	iquitmustdash.com © 2013
  </small>
</footer>

app/views/layouts/_header.html.erb
<header class="center">
  	<% if true %>
  	<div class="header-item">
  	<ul id="nav-menu">
  		<li id="nav-item-play" class="nav-item">
			<%= link_to "Play", root_path %>
		</li>
  		<li id="nav-item-levels" class="nav-item">
			<%= link_to "Levels", levels_path %>
		</li>
  	</ul>
  </div>
  <% end %>
  	<div class="header-item desktop-only">
      <%= link_to image_tag("logo.png", border: 0), "https://t.co/H6stw47FE1" %>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!-- [if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
  <head>
    <title>I Quit Must Dash</title>
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
	<script src="http://ajax.googleapis.com/ajax/libs/swfobject/2.2/swfobject.js" type="text/javascript"/></script>
	<script type="text/javascript">
		var flashvars = {
			<% if @level %>
			level: "<%= @level.id %>",
			<% end %>

			<% if @replay and @replay != "" %>
			replay: "<%= @replay %>"
			<% end %>
		};
		var params = {
			menu: "false",
			wmode: "direct"
		};
		var attributes = {
			id: "iqmd",
			name: "iqmd"
		};

		swfobject.embedSWF("/assets/iqmd.swf", "flashcontent", "640", "576", "11.0.0","expressInstall.swf", flashvars, params, attributes);
    </script>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container" id="main">
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/levels/_form.html.erb
<%= form_for @level do |f| %>
  <% if @level.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@level.errors.count, "error") %> prohibited this level from being saved:</h2>

      <ul>
      <% @level.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :tiles %><br />
    <%= f.text_field :tiles %>
  </div>
  <div class="field">
    <%= f.label :objects %><br />
    <%= f.text_field :objects %>
  </div>
  <div class="field">
    <%= f.label :enemies %><br />
    <%= f.text_field :enemies %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/levels/edit.html.erb
<h1>Editing level</h1>

<%= render 'form' %>

<%= link_to 'Show', @level %> |
<%= link_to 'Back', levels_path %>

app/views/levels/index.html.erb
<div id="levels">
<div id="levels_latest" class="levels_column">
  <h2>Latest Levels</h2>
 <% @levels_latest.each do |level| %>
  <div class="level">
    <p><%= level.created_at.to_formatted_s(:short) %></p>
    <%= link_to image_tag(level.icon.url, border: 1, class: "level_img"), level %>
    <p><%= level.plays %> plays</p>
  </div>
 <% end %>
</div>
<div id="levels_popular" class="levels_column">
  <h2>Popular Levels</h2>
 <% @levels_popular.each do |level| %>
  <div class="level">
    <p><%= level.created_at.to_formatted_s(:short) %></p>
    <%= link_to image_tag(level.icon.url, border: 1, class: "level_img"), level %>
    <p><%= level.plays %> plays</p>
  </div>
 <% end %>
</div>
</div>

<% if false %>

<table>
  <tr>
    <th>Tiles</th>
    <th>Objects</th>
    <th>Enemies</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @levels_latest.each do |level| %>
  <tr>
    <td><%= level.tiles %></td>
    <td><%= level.objects %></td>
    <td><%= level.enemies %></td>
    <td><%= link_to 'Show', level %></td>
    <td><%= link_to 'Edit', edit_level_path(level) %></td>
    <td><%= link_to 'Destroy', level, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>
<% end %>

app/views/levels/new.html.erb
<h1>New level</h1>

<%= render 'form' %>

<%= link_to 'Back', levels_path %>

app/views/levels/show.html.erb
<div class="center">
	<p id="notice"><%= notice %></p>
<div id="flashcontent">
	<h1>You need to download the latest <a href="https://get.adobe.com/flashplayer/?no_ab=1">Flash Player Version</a> to run this game</h1>
</div>
	<h3><%= @level.plays %> plays</h3>
	<h3>Submitted on <%= @level.created_at.to_formatted_s(:short) %></h3>
</div>

app/views/static_pages/home.html.erb
<div class="center">
	<% if false %>
  <iframe width="560" height="315" src="//www.youtube.com/embed/-iwErum1Qcg?hd=1&autohide=1&showinfo=0&wmode=opaque" frameborder="0" allowfullscreen></iframe>
  <% else %>
	<div id="flashcontent">
		<h1>You need to download the latest <a href="https://get.adobe.com/flashplayer/?no_ab=1">Flash Player Version</a> to run this game</h1>
	</div>
	<% end %>
  	<ul id="share-menu">
  		<li class="share-item">
			<%= link_to image_tag("facebook.png", border: 0), "https://www.facebook.com/mustdashgame" %>
		</li>
  		<li class="share-item">
			<%= link_to image_tag("twitter.png", border: 0), "https://twitter.com/jayrob_in" %>
		</li>
  		<li class="share-item">
			<%= link_to image_tag("blog.png", border: 0), "http://jayrob.in/" %>
		</li>
  	</ul>
</div>